#!/usr/bin/env python3
"""
Script to set up .env file for waitlist_backend with Google Sheets credentials
"""
import os
from pathlib import Path

# Get the directory where this script is located
script_dir = Path(__file__).parent
env_file = script_dir / ".env"

# Environment variables to set
env_vars = {
    "GOOGLE_SERVICE_ACCOUNT_EMAIL": "clinicflow-waitlist@clinicflows-483507.iam.gserviceaccount.com",
    "GOOGLE_PROJECT_ID": "clinicflows-483507",
    "GOOGLE_SHEETS_SPREADSHEET_ID": "1BJzP0HSVfTv6DbLcqrTIRzmcVRSjKVaEtBubp963gHc",
    "GOOGLE_SERVICE_ACCOUNT_FILE": "clinicflows-483507-5d1e02eb1a43.json",
    "GOOGLE_PRIVATE_KEY": """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDKNiXo0eexwH12
uban9xI8j4ivgVkBu5IQYIucUGno/8LIdIJdNSx1uAVDluln6etMngwDZEDlenIG
3sBGZzvL3JgrgNUT5FpYYolmAcqr31Jb2HHsHgiANJJaNQZmu4HDEsWbwGew3xPe
a1DuWw86xb2LV0zZZ9jMvmiC3sdWpPdRXSSJ5cq0FUp9cADK3JDyHr2bPL2pX35y
4dlpOSW37U10rD6i4+hT08+wuoYoZ7ocbYjVXKWQGyelapo65x01PAPZ4ZQuA2G/
hwhp3OFoOro1wnCy5baX6/Kqo7GjMyWaxOdpYboLNQ6UCoHY4z2FPTm7pqlpcpyw
CQhfgX6jAgMBAAECggEAR0p+5A35G0yLj0ubb61mcw6BuKqoODmqnfaD0ijxphFh
2W1mNrlUAu7NgE5Y3Od2Ky1/e8ShMqaQRAbNkCS+Srnrtk62EMzN42JeIaYZD65s
6W+ufnn6MkUWohIWvyp1bdKU87wKcqu7ZAu+3UIiZOypTlKJiA6aO1kYHKexbMSc
FDkm3arUQWY0u9jLCAbQuM10hJbCOxXZeR/kKoUoOMGKbFepw6J/K4sfypJrXev0
Ad84h7WqFA6JGDrHH7xXzb0CZrfhDLbsBexSPgxCqaTnwxeMNjd1swj7BbTT0eEE
YYx+htjU/aCw+J+g4IdWuFBQhBAmYEd/OB0jTTqU2QKBgQD8mXPbjDqLUG2WXYGJ
6wl/QSMZW5lbjnVNnbwhavsOgAHTiziBuxmHl91m54pV9NmxgBoldCbO7FroH6I1
5blhgim3z3WC+Us2zfUmjVrE9s/3zV+HJUJ6vQQXohwa+7TUM0Y+gCwRwiSFrpiR
WG9/TDgSS5D3PRdtS1ZdFLnD6wKBgQDM7wp2R+OcRzmoz9YwtYkJtQlBQHMSk9CN
R/vGDHFqETRqt6/jUK2n+Fwa+iWO3gtbHe65t+f3vM/RoGLnf6LWt1sWqu3sP7SF
GaQYZvbwEJBXrYlOK3s/mDLp7u6OfH7JNoNfk6eGO4/jZYejjVdCmarOpxfbcKhq
ZBy/CwHaKQKBgQDe/5Xhr8WLcgCdK4WNvXqP5nBXFZ+ozXZPhD4u/mQPZAC4wgKr
vQKHyxFBpI1i3xtEcYQjpowQR2bl3+9zR5BGPgQYasUiUHUPN/oCA+6rTf1BlgSM
qd8rviybtJi9VZNJds6/pKXDM7LMddvpDLq6Fg62UBH1wvAoo8blu8NX6wKBgF3l
uNlxHuzgBZ8/e1heFSgJdvAa457Dc28IaGfaE60RrP6oo0J4GNk5hpolu0e2nWVm
VZdqmDJ+pInb/vUrGiVfZbEBKHpyxfemQ/WaV9KvBDPoI11ZtuLwjYN6InvOtxji
jVchhESQzeDXCEr729t8JTMChH/bIo98x18RYAvhAoGBAL8uky1GSe0CK757x0+O
MEUUdFBdLDBLlB+pN/PO5ZKHSca9kIYuw41NnJ6bO5MCHh6lZEiEWYUHkIqAiA85
hOCFXM73ZidxvAt3ThxHfwF0TRIiJY0m6R9NCN24c2CCe4NidjaQaysQI2hXQ6+3
fdVBNNTNq3dIM8ckIDLxpFTn
-----END PRIVATE KEY-----""".replace("\n", "\\n")
}

def write_env_file():
    """Write environment variables to .env file"""
    lines = ["# Google Sheets Configuration\n"]
    lines.append("# Generated by setup_env.py\n\n")
    
    for key, value in env_vars.items():
        if key == "GOOGLE_PRIVATE_KEY":
            # Private key needs to be in quotes with escaped newlines
            lines.append(f'{key}="{value}"\n')
        else:
            lines.append(f"{key}={value}\n")
    
    try:
        with open(env_file, 'w', encoding='utf-8') as f:
            f.writelines(lines)
        print(f"Successfully created .env file at {env_file}")
        print("\nEnvironment variables set:")
        for key in env_vars.keys():
            print(f"  - {key}")
        return True
    except Exception as e:
        print(f"Error creating .env file: {e}")
        print(f"\nPlease manually create .env file with the following content:")
        print("\n" + "="*60)
        for key, value in env_vars.items():
            if key == "GOOGLE_PRIVATE_KEY":
                print(f'{key}="{value}"')
            else:
                print(f"{key}={value}")
        print("="*60)
        return False

if __name__ == "__main__":
    write_env_file()

